- variables.scss
Hey Guys,
I changed some of the values of the spacings variables and want to know, whether the new values are implementable without any conflicts?
here a link to the file in InVision: https://zalando.invisionapp.com/d/main#/console/10454474/222275516/preview
> Replacing values of design system spacings

- .gitignore
- gulpfile.js
- index.scss
- package.json
Set up for stylelint with an existing sass config setting (a best practice rule set from OSS).
This should be discussed as I believe that everyone is doing SCSS/CSS differently and we have to decide.
> Setting up linting for css (tbd)

- components/base/_icons.scss
> Fix icon showing

- circle.yml
Added circleci config to build and lint the scss repository and build the upstream repo "demo" and publish the build to gh-pages
> Added circleci config

- circle.yml
Removed test branch from demo dependency
> Removed test branch

- atoms/_icons.scss
- molecules/_dropdown.scss
- utils/variables/_basics.scss
- Fixed spacings
- Adjusted active color
- Fixed style of child menu's 
NEW|OLD
------------ | -------------
> Adjusted spacings and colors of dropdown regarding latest design

- doc/elements/badge.md
- doc/elements/pagination.md
Create docs for pagination and badge
> Add docs for pagination and badge

- molecules/_tables.scss
- Realigned sorting
- Added styles for ws-dropdown filter in table headers
> Fixed tables for new table filter design

- atoms/_badges.scss
Improved style of badges
Previous
After
> feature(badges) Improved styling of badges

- atoms/_buttons.scss
- atoms/_forms.scss
- molecules/_dropdown.scss
- utils/_typography.scss
Added styles for anchors, buttons and custom selects in disabled state as dropdown trigger
> Added disabled styles for dropdown triggers

- CONTRIBUTING.md
- LICENSE
- MAINTAINERS
- README.md
- code-of-conduct.md
fix(docs): Updating README
Added some initial docs / readme / contributing markdown files for scss project
> fix(docs): Updating README

- utils/variables/_colors.scss
Added a yellow color palette & changed the value of the variable "madang".
> Added & changed colors

- atoms/_cards.scss
- atoms/typography/_headings.scss
I had a small QA session with Mehment and this is the outcome.
> Fixed feedback from qa session

- atoms/_buttons.scss
Fixed the styling of normal disabled buttons
> fix(buttons): Fixed styling of disabled buttons

- README.md
This PR fixes the link in the README to the CONTRIBUTING file.
> Fix link to the CONTRIBUTING file

- atoms/toggle/_switch.scss
#106
Fix for displaying switch correctly on Firefox.
> fix(switch): fixed for firefox

- atoms/_cards.scss
> Card radius removed

- doc/general/1-intro.md
- doc/general/2-colors.md
- doc/general/3-spacing.md
- doc/general/4-typography.md
- doc/general/5-navigation.md
- doc/general/6-structure.md
- doc/general/7-overlays.md
- doc/general/8-feedback.md
Pics moved to proper place + some small adjustments
> documentation update

- doc/designsystem/spacings.md
- doc/general/3-spacing.md
- utils/variables/_spacings.scss
- changed $space-xxl to 3rem
- added variable $space-xxxl with 4rem
@tonysaad @wholesale-design-system/engineers @inanda This might be a breaking change for your applications so if you update to a new version of the scss repository keep track on that!
> feat(spacing): Changed value of $space-xxl to 3rem

- atoms/typography/_labels.scss
- doc/designsystem/spacings.md
- doc/general/3-spacing.md
- doc/molecules/tables.md
- molecules/_dropdown.scss
- molecules/_tables.scss
- utils/_schemas.scss
- utils/variables/_breakpoints.scss
- utils/variables/_spacings.scss
Issue: #51 
- Updated the table design according to mockup in invision https://zalando.invisionapp.com/share/F5CHIU3TY#/248273871_Table_Solutions_V6
- Made active dropdown item not bold
- Fixed tabled breakpoint
- Added class to make labels clickable
> Implemented new table design

- .editorconfig
- circle.yml
- gulpfile.js
- package.json
- copied gulp tasks for version and changelog generation and release creation
- added steps to circle.yml to release automatically new versions
- added editor config
> feat(deployment): Added automatic version release process

- atoms/_badges.scss
- atoms/typography/_headings.scss
- doc/molecules/tables.md
- molecules/_radio-group.scss
- molecules/_tables.scss
- utils/_schemas.scss
Based on our new design I adjusted the styleguide to follow the new rules.
https://zalando.invisionapp.com/d/main#/projects/prototypes/10411531
- Added flat tables without shadow and outer border
- Fixed radio group button colors
- Fixed badge colors and sizes
> Design adjustments

- molecules/_header.scss
- package-lock.json
As described in #91 we need the SCSS code from the component to be part of the scss itself as for our use case we just need the navigation bar without anything. 
This PR is basically copy&pasting the scss from the component (no refactoring for now)
> feat(molecules): Adding dedicated SCSS for header

- circle.yml
This should fix the circleci build
> fix(build): Fixed circle ci build

- circle.yml
- gulpfile.js
Sadly,
I forgot doing the build step also in Tests.
> fix(ci): Fix circleCI

- circle.yml
I should definitely check how to do a manual circleCI YAML file check, this time forgot to change the path in the deployment command ...
> fix(ci): sadly I forgot to change the deployment path

- atoms/_buttons.scss
- atoms/_forms.scss
- atoms/toggle/_base.scss
- atoms/toggle/_checkbox.scss
- atoms/toggle/_radio.scss
- atoms/toggle/_switch.scss
- circle.yml
- molecules/_tables.scss
- package.json
#106 As described here, for the Retail Portal allowing the use of Fabric means, that it should not provide direct DOM tag stylings, this creates UX issues.
> [WIP] feat(atoms): changing DOM tag stylings to be class based

- circle.yml
Adding config for v2 ci deployment. Had to change ordering.
> Fix ci for v2
